### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Vinzz-sm** [pachdomenic/twrp_device_samsung_a02#1]
Please teach me how to use it

**Comment by Vinzz-sm** [comment]
I dont now because the files format is not .img

**Comment by cat658011** [comment]
![изображение](https://github.com/user-attachments/assets/564dc402-a5b5-4bc8-9f69-9c8f0b5062bb)

**Comment by pachdomenic** [comment]
It is a DeviceTree, used to Build TWRP
